version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: django
    versions:
    - "3.2"
  - dependency-name: asgiref
    versions:
    - 3.3.2
    - 3.3.4
  - dependency-name: pytz
    versions:
    - "2021.1"
