#
# modify ${{ PROJECT_NAME }} to your python code src
#
name: Pylama Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        py_version: [ "3.9", "3.10", "3.11" ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py_version }}

      - name: Install Pylama
        run: |
          python -m pip install pylama

      - name: Install Requirements
        run: |
          python -m pip install -r requirements.txt

      - name: Run Lint
        run: |
          pylama django_qiyu_utils
